---
env:
  TZ: UTC

protonmailBridge:
  login:
    enabled: true
  certificate:
    enabled: true

service:
  main:
    controller: main
    ports:
      smtp:
        port: 25
      imap:
        port: 143

persistence:
  root:
    enabled: true
    storageClass: "-"
    size: 1Gi
    accessMode: ReadWriteOnce
  login:
    enabled: true
    type: secret
    name: protonmail-bridge-login-secret
  cert:
    enabled: true
    type: secret
    name: protonmail-bridge-certificate-secret
